services:
  ## Database
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5431:5432
    volumes:
      - ./postgres-storage:/var/lib/postgresql/data
    env_file: .env
