services:
  ## Database
  db:
    container_name: api-db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres-storage:/var/lib/postgresql/data
    env_file: .env.local
